### ISSUE TITLE
Refactor into beast_http directory

### ISSUE THREAD

**Issue by NAThompson** [0xdead4ead/BeastHttp#18]
As I include your code into my own, you have files like <basic_router.hxx> which perhaps needs to be put in my syspath to work. However, more idiomatic would be a directory structure of the form <beast_http/basic_router.hxx>, which would allow visual distinction of dependency code.

Also, this would allow some understanding of what constitutes the public API, as currently I don't understand whether I should be #include'ing files in `base/` `reactor/` and `shared/`.

**Comment by 0xdead4ead** [comment]
Ok, I will think about it!
